name: "Build QAX"
description: "Build the QAX program."

inputs:
  env-name:
    description: "Name for Conda environment"
    required: true
    default: "build-qax"

outputs:
  version:
    description: "QAX build version id"
    value: ${{ steps.qax-version.outputs.version }}

runs:
  using: "composite"
  steps:
    - name: Install QAX
      shell: bash -l {0}
      run: |
        conda activate ~/miniconda/envs/${{ inputs.env-name }}
        pip install .

    - id: qax-version
      name: QAX Version
      shell: bash -l {0}
      run: |
        conda activate ~/miniconda/envs/${{ inputs.env-name }}
        echo "version=$(python -m setuptools_scm)" >> "$GITHUB_OUTPUT"

    # yes we could have a separate job, specificially a sphinx build action
    # and then upload the artifact and then download it within the win-builder.
    # However, for a distributable build, it makes more sense to build everything
    # from the same environment rather than separate jobs to ensure consistency.
    - name: Docs-build
      shell: bash -l {0}
      run: |
        conda activate ~/miniconda/envs/${{ inputs.env-name }}
        conda info --envs
        sphinx-build -b html docs docs/_build/html
        # sphinx-build -b latexpdf docs docs/_build/latex
