name: QAX Build

on:
  push:
    branches:
      - 'composite-actions'
  workflow_dispatch:

jobs:
  build:
    # whilst we might never need it, it does however fleshout the idea of multiple os and py builds
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["windows-latest"]
        python-version: ["3.10"]

    env:
      # mostly used as helpers for retrieving as env vars within inno setup
      # VERSION: "v10.0.0.dev0"
      WORKDIR: ${{ github.workspace }}
      CONDA_ENV: "build-qax"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Establish Env
        uses: ./.github/actions/environment
        with:
          env-name: "${{ env.CONDA_ENV }}"

      - name: Test dir
        shell: bash -l {0}
        run: |
          ls -la
          ls .github/
          ls -l .github/actions
          ls -l .github/actions/build

      - name: Build QAX
        id: qax-build
        uses: ./.github/actions/build
        with:
          env-name: "${{ env.CONDA_ENV }}"

      - name: Upload
        uses: ./.github/actions/upload
        with:
          dist-name: "qax_dist_${{ steps.qax-build.outputs.version }}"
          dist-path: "qax_dist_${{ steps.qax-build.outputs.version }}.tar.gz"
          setup-name: "qax_setup_${{ steps.qax-build.outputs.version }}"
          setup-path: "qax_setup_${{ steps.qax-build.outputs.version }}.exe"
